# SonarCloud Project Configuration
sonar.projectKey=OryxSSJ_BioVirtualPrototipo_Team06
sonar.organization=oryxssj
sonar.projectName=BioVirtualPrototipo
sonar.branch.name=master

# Sources and Tests
sonar.sources=app, admin, login
sonar.tests=tests

# Exclusions to focus on custom code only
sonar.exclusions=public/plugins/**, **/vendor/**

# Encoding
sonar.sourceEncoding=UTF-8

# Report Paths
sonar.php.coverage.reportPaths=reports/coverage.xml
sonar.php.tests.reportPath=reports/unit-tests.xml